export default function Searchbar({
  preactive,
  checked,
  label,
  id,
  name,
  type,
  inputcustomclasses,
  customclasses,
  bg,
  color,
  placeholder,
  queryid,
  searchquerynames,
  searchquerylinks,
  collapseonmobile,
  dir,
  labelclasses,
  inputcovercustomclasses,
  reslistcustomclasses,
  customstyles,
  formclasses,
  outformclasses,
  dev,
}) {
  return <axg-element
    mode='searchbar_v3'
    dev={dev}
    reslistcustomclasses={reslistcustomclasses}
    preactive={preactive}
    checked={checked}
    label={label}
    id={id}
    name={name}
    type={type}
    inputcustomclasses={inputcustomclasses}
    customclasses={customclasses}
    bg={bg}
    color={color}
    placeholder={placeholder}
    queryid={queryid}
    searchquerynames={JSON.stringify(searchquerynames)}
    searchquerylinks={JSON.stringify(searchquerylinks)}
    collapseonmobile={collapseonmobile}
    dir={dir}
    labelclasses={labelclasses}
    inputcovercustomclasses={inputcovercustomclasses}
    customstyles={customstyles}
    formclasses={formclasses}
    outformclasses={outformclasses}
  ></axg-element>
}